server:
  port: 8082  # Port pour le service voiture

spring:
  application:
    name: SERVICE-CAR  # Nom du service tel qu'il apparaîtra dans Eureka
  datasource:
    url: jdbc:postgresql://localhost:5432/voitureservicedb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update  # Crée ou met à jour automatiquement le schéma
    show-sql: true  # Affiche les requêtes SQL générées

# Configuration Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true